### ISSUE TITLE
User should not be prompted for push notification permission immediately

### ISSUE THREAD

**Issue by goodgravy** [trigger-corp/trigger.io-parse#1]
Users will be more likely to accept incoming push notifications after they've used the app and better understand the need.

Currently, the push notification permission prompt appears when the app is first run. It should be (optionally?) deferred until later, when a new API (e.g. `forge.parse.push.enable()`) is used.

**Comment by prud** [comment]
@antoinevg this has already been solved quite a while ago, right?

**Comment by antoinevg** [comment]
Indeed it has :-) `delayRegistration` in the module config
